/**
 * Unrag ASCII logo source.
 *
 * Original provided as `logo.txt` at the repo root (22 lines, width ~150).
 * We embed it here so the debug TUI stays self-contained when published.
 *
 * Legend:
 * - `g` = filled pixel (rendered as a colored block)
 * - `u` = empty pixel (rendered as whitespace)
 */
export const UNRAG_LOGO_LINES: string[] = [
  "gggggggggguuuuuugggggggggguuuuugggggggguuuuuuuuggggggggguuuuuuggggggggggggggggguuuuuuuuuuuuuuuuuuuuuggggggggggguuuuuuuuuuuuuuuuuuuggggggggggggguuuuuuu",
  "gggggggggguuuuuugggggggggguuuuuggggggggguuuuuuuggggggggguuuuuugggggggggggggggggggguuuuuuuuuuuuuuuuuggggggggggggguuuuuuuuuuuuuuuuggggggggggggggggguuuuu",
  "gggggggggguuuuuugggggggggguuuuugggggggggguuuuuuggggggggguuuuuugggggggggggggggggggggguuuuuuuuuuuuuuuggggggggggggguuuuuuuuuuuuuugggggggggggggggggggguuuu",
  "gggggggggguuuuuugggggggggguuuuuggggggggggguuuuuggggggggguuuuuuggggggggggggggggggggggguuuuuuuuuuuuugggggggggggggguuuuuuuuuuuuuggggggggggggggggggggggguu",
  "gggggggggguuuuuuggggguuuuuuuuuuggggggggggguuuuuggggggggguuuuuugggggggggggggggggggggggguuuuuuuuuuuuggggggggggggggguuuuuuuuuuugggggggggggggggggggggggggu",
  "gggggggggguuuuuuuuuuuuuuuuuuuuugggggggggggguuuuggggggggguuuuuuggggggggggggggggggggggggguuuuuuuuuugggggggggggggggguuuuuuuuuuggggggggggggguugggggggggggu",
  "ggggggggguuuuuuuuuuuuuuggguuuuuggggggggggggguuuggggggggguuuuuugggggggggguuuuggggggggggguuuuuuuuuuggggggggggggggggguuuuuuuuuggggggggggguuuuuggggggggggg",
  "gggggguuuuuuuuuuuggggggggguuuuugggggggggggggguuggggggggguuuuuugggggggggguuuuugggggggggguuuuuuuuuuggggggggggggggggguuuuuuuuugggggggggguuuuuuugggggggggg",
  "uuuuuuuuuuuuuuuugggggggggguuuuugggggggggggggguuggggggggguuuuuugggggggggguuuuugggggggggguuuuuuuuuggggggggggggggggggguuuuuuugggggggggguuuuuuuugggggggggg",
  "uuuuuuuggguuuuuugggggggggguuuuuggggggggggggggguggggggggguuuuuugggggggggguuuugggggggggguuuuuuuuuuggggggggguggggggggguuuuuuugggggggggguuuuuuuuuuuuuuuuuu",
  "uugggggggguuuuuugggggggggguuuuuggggggggggggggggggggggggguuuuuugggggggggggggggggggggggguuuuuuuuugggggggggguggggggggguuuuuuugggggggggguuuugggggggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggggggggggggggggggguuuuuugggggggggggggggggggggguuuuuuuuuuuggggggggguugggggggggguuuuuugggggggggguuuugggggggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggggggggggggggggggguuuuuugggggggggggggggggggguuuuuuuuuuuugggggggggguuuggggggggguuuuuugggggggggguuuugggggggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggguggggggggggggggguuuuuuggggggggggggggggggggggguuuuuuuuuggggggggguuuugggggggggguuuuugggggggggguuuugggggggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggguugggggggggggggguuuuuugggggggggggggggggggggggguuuuuuuuggggggggggggggggggggggguuuuugggggggggguuuugggggggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggguuuggggggggggggguuuuuuggggggggggugggggggggggggguuuuuugggggggggggggggggggggggguuuuuggggggggggguuuuuuuuggggggggg",
  "gggggggggguuuuuugggggggggguuuuuggggggggguuuggggggggggggguuuuuugggggggggguuuuugggggggggguuuuuuggggggggggggggggggggggggguuuuuggggggggggguuuuuugggggggggg",
  "ggggggggggguuuugggggggggguuuuuuggggggggguuuugggggggggggguuuuuugggggggggguuuuugggggggggguuuuugggggggggggggggggggggggggguuuuuggggggggggggguuuggggggggggg",
  "ggggggggggggggggggggggggguuuuuuggggggggguuuuuggggggggggguuuuuugggggggggguuuuugggggggggguuuuuggggggggggggggggggggggggggguuuuugggggggggggggggggggggggggg",
  "uggggggggggggggggggggggguuuuuuuggggggggguuuuuugggggggggguuuuuugggggggggguuuuugggggggggguuuuuggggggggguuuuuuuugggggggggguuuuuuggggggggggggggggggggggggg",
  "uuggggggggggggggggggggguuuuuuuuggggggggguuuuuugggggggggguuuuuugggggggggguuuuuugggggggggguuugggggggggguuuuuuuuugggggggggguuuuuugggggggggggggggggggggggg",
  "uuuugggggggggggggggggguuuuuuuuuggggggggguuuuuuuggggggggguuuuuugggggggggguuuuuugggggggggguuuggggggggguuuuuuuuuugggggggggguuuuuuuugggggggggggggggugggggg",
  "uuuuuuugggggggggggguuuuuuuuuuuuggggggggguuuuuuuugggggggguuuuuuggggggggguuuuuuugggggggggguugggggggggguuuuuuuuuugggggggggguuuuuuuuuuuggggggggggguugggggg",
];

